
seed: 0

data:
  resize: 256
  imagesize: 224
  inputsize: 224

model:
  backbone_names: ["wideresnet50"]
  layers_to_extract: ["layer2", "layer3"]
  embedding_to_extract_from: "avgpool"
  embedding_extractor_iter: 200

  coreset_model_name: "ablationtailedpatch"
  tail_th_type: "ada_trim_min-mode"
  tail_data_augment_type: 'rotflip'
  tail_lof: false

  greedy_ratio: 0.1
  greedy_proj_dim: 128

  faiss_k_neighbor: 1

