
seed: 0

data:
  resize: 256
  imagesize: 224
  inputsize: 224

model:
  backbone_names: ["wideresnet50"]
  layers_to_extract: ["layer2", "layer3"]
  embedding_to_extract_from: "avgpool"

  coreset_model_name: "atailedpatch"
  tail_th_type: "symmin"
  data_augment_tail: true
  tail_lof: true

  greedy_ratio: 0.1
  greedy_proj_dim: 128

  faiss_k_neighbor: 1

