
seed: 0

data:
  resize: null
  imagesize: 448
  inputsize: 224
  overlap_ratio: 0.5
  roi: [1900, 36, 6380, 4964]

model:
  backbone_names: ["wideresnet50"]
  layers_to_extract: ["layer2", "layer3"]

  coreset_model_name: "patchcore"

  greedy_ratio: 0.01
  greedy_proj_dim: 128

  faiss_k_neighbor: 1

