
seed: 0

data:
  resize: 256
  imagesize: 224
  inputsize: 224

model:
  backbone_names: ["densenet201"]
  layers_to_extract: ["features.denseblock2", "features.denseblock3"]
  embedding_to_extract_from: "global_pool"

  coreset_model_name: "tailedpatch"

  greedy_ratio: 0.1
  greedy_proj_dim: 128

  faiss_k_neighbor: 1

